# Generated by Django 2.2.5 on 2019-09-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='profile_image',
        ),
    ]
