# Generated by Django 2.2.5 on 2019-09-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190925_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='porfile_image',
            new_name='profile_image',
        ),
    ]
